{"name": "test_fail_update_task", "status": "failed", "statusDetails": {"message": "AssertionError: Текст ошибки не совпадает с ожидаемым - Status does not exist\nassert 'Authorizatio...ader required' == 'Status does not exist'\n  \n  - Status does not exist\n  + Authorization header required", "trace": "self = <clickup_tests.tests.api.test_tasks.TestTasks object at 0x000001E3EEBE7710>, tasks_client = <api_clients.tasks.TasksClient object at 0x000001E3EEBE4A40>\ncreate_and_delete_task = {'archived': False, 'assignees': [], 'checklists': [], 'creator': {'color': '', 'email': 'sanches2101@gmail.com', 'id': 182699604, 'profilePicture': None, ...}, ...}\n\n    @allure.description(\"Проверка ошибки при обновлении задачи с некорректным статусом\")\n    def test_fail_update_task(self, tasks_client, create_and_delete_task):\n        task_id = create_and_delete_task[\"id\"]\n    \n        with allure.step(\"Обновляем заголовки на POST\"):\n            tasks_client.session.headers.update(CLICKUP_POST_HEADER)\n    \n        with allure.step(\"Отправляем PUT-запрос с несуществующим статусом\"):\n            response = tasks_client.update_task(task_id=task_id, payload=CLICKUP_BAD_PAYLOAD)\n        assert response.status_code == 400\n    \n        with allure.step(\"Проверяем ошибку в теле ответа\"):\n            body = response.json()\n>           assert body.get(\"err\") == \"Status does not exist\", \"Текст ошибки не совпадает с ожидаемым - Status does not exist\"\nE           AssertionError: Текст ошибки не совпадает с ожидаемым - Status does not exist\nE           assert 'Authorizatio...ader required' == 'Status does not exist'\nE             \nE             - Status does not exist\nE             + Authorization header required\n\ntests\\api\\test_tasks.py:94: AssertionError"}, "description": "Проверка ошибки при обновлении задачи с некорректным статусом", "steps": [{"name": "Обновляем заголовки на POST", "status": "passed", "start": 1744826066430, "stop": 1744826066430}, {"name": "Отправляем PUT-запрос с несуществующим статусом", "status": "passed", "start": 1744826066430, "stop": 1744826066502}, {"name": "Проверяем ошибку в теле ответа", "status": "failed", "statusDetails": {"message": "AssertionError: Текст ошибки не совпадает с ожидаемым - Status does not exist\nassert 'Authorizatio...ader required' == 'Status does not exist'\n  \n  - Status does not exist\n  + Authorization header required\n", "trace": "  File \"c:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\tests\\api\\test_tasks.py\", line 94, in test_fail_update_task\n    assert body.get(\"err\") == \"Status does not exist\", \"Текст ошибки не совпадает с ожидаемым - Status does not exist\"\n"}, "start": 1744826066502, "stop": 1744826066502}], "start": 1744826066430, "stop": 1744826066503, "uuid": "31fc448c-e483-49f2-babb-03b3ddc4f178", "historyId": "93a51c71bf9f1aaacb1b43954b741361", "testCaseId": "93a51c71bf9f1aaacb1b43954b741361", "fullName": "tests.api.test_tasks.TestTasks#test_fail_update_task", "labels": [{"name": "feature", "value": "API: Работа с задачами"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "Grw-pc"}, {"name": "thread", "value": "28392-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}