{"name": "test_fail_update_task", "status": "failed", "statusDetails": {"message": "Failed: ScopeMismatch: You tried to access the function scoped fixture tasks_client with a session scoped request object. Requesting fixture stack:\ntests\\conftest.py:43:  def get_list_id(tasks_client)\nRequested fixture:\ntests\\conftest.py:22:  def tasks_client()", "trace": "ScopeMismatch: You tried to access the function scoped fixture tasks_client with a session scoped request object. Requesting fixture stack:\ntests\\conftest.py:43:  def get_list_id(tasks_client)\nRequested fixture:\ntests\\conftest.py:22:  def tasks_client()"}, "description": "Проверка ошибки при обновлении задачи с некорректным статусом", "start": 1744825760353, "stop": 1744825760353, "uuid": "0e5056b9-143e-413e-8dee-8979c640cb2f", "historyId": "93a51c71bf9f1aaacb1b43954b741361", "testCaseId": "93a51c71bf9f1aaacb1b43954b741361", "fullName": "tests.api.test_tasks.TestTasks#test_fail_update_task", "labels": [{"name": "feature", "value": "API: Работа с задачами"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "Grw-pc"}, {"name": "thread", "value": "31176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}