{"name": "test_fail_get_task", "status": "failed", "statusDetails": {"message": "Failed: ScopeMismatch: You tried to access the function scoped fixture tasks_client with a session scoped request object. Requesting fixture stack:\ntests\\conftest.py:43:  def get_list_id(tasks_client)\nRequested fixture:\ntests\\conftest.py:22:  def tasks_client()", "trace": "ScopeMismatch: You tried to access the function scoped fixture tasks_client with a session scoped request object. Requesting fixture stack:\ntests\\conftest.py:43:  def get_list_id(tasks_client)\nRequested fixture:\ntests\\conftest.py:22:  def tasks_client()"}, "description": "Проверка ошибки при получении задач с некорректными заголовками", "start": 1744799822025, "stop": 1744799822025, "uuid": "8580f878-5e5f-476c-bec3-750b376aa13d", "historyId": "7cb619b02365d2ca8bb60f9dd5fa326a", "testCaseId": "7cb619b02365d2ca8bb60f9dd5fa326a", "fullName": "tests.api.test_tasks.TestTasks#test_fail_get_task", "labels": [{"name": "feature", "value": "API: Работа с задачами"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "Grw-pc"}, {"name": "thread", "value": "8224-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}