{"uuid": "7e43dfa0-47b0-4cd6-8db0-dcb871fd92d4", "children": ["db7cf7a8-ef73-47f5-9505-5afc9227096f"], "befores": [{"name": "authorized_user", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TargetClosedError: Page.goto: Target page, context or browser has been closed\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\n", "trace": "  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"c:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\tests\\conftest.py\", line 70, in authorized_user\n    login_page.login(CLICKUP_EMAIL, CLICKUP_PASSWORD)\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\pages\\login_page.py\", line 14, in login\n    self.navigate_to()\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\pages\\base_page.py\", line 18, in navigate_to\n    self.page.goto(full_url)\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9020, in goto\n    self._sync(\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 552, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "steps": [{"name": "Запуск браузера и выполнение авторизации через UI", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TargetClosedError: Page.goto: Target page, context or browser has been closed\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\n", "trace": "  File \"c:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\tests\\conftest.py\", line 70, in authorized_user\n    login_page.login(CLICKUP_EMAIL, CLICKUP_PASSWORD)\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\pages\\login_page.py\", line 14, in login\n    self.navigate_to()\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\pages\\base_page.py\", line 18, in navigate_to\n    self.page.goto(full_url)\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9020, in goto\n    self._sync(\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 552, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "steps": [{"name": "Вход в систему", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TargetClosedError: Page.goto: Target page, context or browser has been closed\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\n", "trace": "  File \"c:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\tests\\conftest.py\", line 70, in authorized_user\n    login_page.login(CLICKUP_EMAIL, CLICKUP_PASSWORD)\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\pages\\login_page.py\", line 14, in login\n    self.navigate_to()\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\pages\\base_page.py\", line 18, in navigate_to\n    self.page.goto(full_url)\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9020, in goto\n    self._sync(\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 552, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "start": 1744799757935, "stop": 1744799760353}], "start": 1744799757409, "stop": 1744799760354}], "start": 1744799757409, "stop": 1744799760355}], "start": 1744799757409, "stop": 1744799760448}