{"name": "test_fail_get_task", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('get_list_id', <FixtureRequest for <Function test_fail_get_task>>)", "trace": "file c:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\tests\\api\\test_tasks.py, line 52\n      @allure.description(\"Проверка ошибки при получении задач с некорректными заголовками\")\n      def test_fail_get_task(self, tasks_client, get_list_id):\nE       fixture 'get_list_id' not found\n>       available fixtures: _verify_url, auth_session, authorized_user, base_url, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, clickup_ids, create_and_delete_task, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, sync_browser, tasks_client, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nc:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\tests\\api\\test_tasks.py:52"}, "description": "Проверка ошибки при получении задач с некорректными заголовками", "start": 1744799742478, "stop": 1744799742478, "uuid": "ed2d8541-f366-422c-bc9f-3cf1f61a96dc", "historyId": "7cb619b02365d2ca8bb60f9dd5fa326a", "testCaseId": "7cb619b02365d2ca8bb60f9dd5fa326a", "fullName": "tests.api.test_tasks.TestTasks#test_fail_get_task", "labels": [{"name": "feature", "value": "API: Работа с задачами"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "Grw-pc"}, {"name": "thread", "value": "25968-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}